### ISSUE TITLE
后端跨域OPTIONS报403，前提，我的其他配置正常

### ISSUE THREAD

**Issue by charlot23** [chfree/think-swagger-ui-vuele#12]
OPTIONS 403 前提配置正确，其他同类型跨域请求没有问题，想请问为啥通过url请求会出现403 ，看过network也是搞不懂，开放了路径也是403，是前端内置了什么吗

**Comment by chfree** [comment]
跨域大多数情况是在后端进行一些允许请求，前端你可以看看【think-swagger-ui-vuele/src/components/util/http/request.js 】这个js里面参考下，是没有什么特殊设置的。

你可以尝试用postman之类的工具先测试下你的请求，看是否会出现同样问题。

如果需要更多帮助，可以给我发邮件chfree365@qq.com并附上一些请求信息和错误信息的截图。
