### ISSUE TITLE
怎么用？

### ISSUE THREAD

**Issue by ldming-com** [chfree/think-swagger-ui-vuele#17]
那个swagger地址填什么？？？

**Comment by luchangtx** [comment]
http://localhost:8080/thinkswagger/index.html

**Comment by ldming-com** [comment]
http://localhost:8080/thinkswagger/index.html 这个地址那来的，用什么提供服务？
http://sw.tennetcn.com/#/  示例也一直无法进入

**Comment by chfree** [comment]
【http://sw.tennetcn.com/#/ 】示例只是一个服务，地址需要填入一个你的后端服务符合swagger的json描述文件
